Strip ANSI from the main branch name
`find` highlights the returned value,
which breaks the `gcm` macro,
it returns 
```
error: pathspec '?[37m?[0m?[41;37mmain?[0m?[37m?[0m' did not match any file(s) known to git
```

I opted in to using `ansi strip` instead of `--no-highlight`,
because I think it covers wider range of nu shell versions